{% set version = "0.3.4" %}

package:
  name: richdem
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/richdem/richdem-{{ version }}.tar.gz
  sha256: a9d3119ca8e25aa73039c94816f68ac2e1c33dc8ef02b0467c090d44243a7ad1

build:
  number: 6
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - rd_depression_filling=richdem.cli:DepressionFilling
    - rd_breach_depressions=richdem.cli:BreachDepressions
    - rd_flow_accumulation=richdem.cli:FlowAccumulation
    - rd_terrain_attribute=richdem.cli:TerrainAttribute
    - rd_info=richdem.cli:RdInfo
    - rd_compare=richdem.cli:RdCompare

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libgdal
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]

  host:
    - python
    - pip
    - numpy
    - libgdal

  run:
    - python
    - setuptools
    - libgdal
    - {{ pin_compatible('numpy') }}
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.15") }}  # [osx and x86_64]

test:
  imports:
    - richdem
  commands:
    - rd_depression_filling --help
    - rd_breach_depressions --help
    - rd_flow_accumulation --help
    - rd_terrain_attribute --help
    - rd_info --help
    - rd_compare --help

about:
  home: https://github.com/r-barnes/richdem
  license: gpl-3.0-or-later
  license_file: LICENSE.txt
  summary: High-Performance Terrain Analysis

extra:
  recipe-maintainers:
    - ocefpaf
    - hobu
