{% set version = "2.3.0" %}

package:
  name: richdem
  version: {{ version }}

source:
  url: https://github.com/r-barnes/richdem/archive/v{{ version }}.tar.gz
  sha256: 5ea5b70a8dde16f19de1b1cbb255bcda34ce5e82039aa004d6f81136fe302a86
  patches:
  - install-shared-lib.patch
  - link-shared-lib.patch
  - include-numeric.patch
  - path-to-string.patch
  - rename-error.patch
  - win32-defs.patch

build:
  number: 0
  # skip: false
  skip: true  # [unix]
  # skip: true  # [(win and vc<14) or py<36]
  entry_points:
    - rd_depression_filling=richdem.cli:DepressionFilling
    - rd_breach_depressions=richdem.cli:BreachDepressions
    - rd_flow_accumulation=richdem.cli:FlowAccumulation
    - rd_terrain_attribute=richdem.cli:TerrainAttribute
    - rd_info=richdem.cli:RdInfo
    - rd_compare=richdem.cli:RdCompare

requirements:
  run_constrained:  # [osx]
        - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - python {{ python }}
    - pybind11
    - libgdal
    - pip

  host:
    - python {{ python }}
    - pip
    - numpy
    - libgdal
    - pybind11

  run:
    - python {{ python }}
    - setuptools
    - libgdal
    - numpy
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  imports:
    - _richdem
    - richdem
  commands:
    - rd_depression_filling --help
    - rd_breach_depressions --help
    - rd_flow_accumulation --help
    - rd_terrain_attribute --help
    - rd_info --help
    - rd_compare --help

about:
  home: https://github.com/r-barnes/richdem
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: High-Performance Terrain Analysis

extra:
  recipe-maintainers:
    - r-barnes
    - mcflugen
    - ocefpaf
    - hobu
