build_platform:
  osx_arm64: osx_64
conda_forge_output_validation: true
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
  win: azure
test_on_native_only: true
azure:
  settings_win:
    pool:
      vmImage: windows-2019
os_version:
  linux_64: cos7
